menu:
  - code: "首页"
    type: "home"
    title: "首页"
    href: "layuimini/page/welcome-1.html?t=1"
    is_shown: 1
  - code: "LAYUI MINI"
    type: "logo"
    title: "LAYUI MINI"
    image: "layuimini/images/logo.png"
    href: ""
    is_shown: 1
  - code: "Expires"
    type: "head"
    title: "Expires"
    icon: "fa fa-address-book"
    href: ""
    target: "_self"
    child: "过期管理"
    is_shown: 1
  - code: "过期管理"
    type: "menu"
    title: "过期管理"
    href: "layuimini/page/expires.html"
    icon: "fa fa-file-text"
    target: "_self"
    is_shown: 1
  - code: "常规管理"
    type: "head"
    title: "常规管理"
    icon: "fa fa-address-book"
    href: ""
    target: "_self"
    child: "主页模板|菜单管理|系统设置|表格示例|表单示例|登录模板|异常页面|其它界面"
    is_shown: 1
  - code: "主页模板"
    type: "directory"
    title: "主页模板"
    icon: "fa fa-home"
    href: ""
    target: "_self"
    child: "主页一|主页二|主页三"
    is_shown: 1
  - code: "主页一"
    type: "menu"
    title: "主页一"
    href: "layuimini/page/welcome-1.html"
    icon: "fa fa-tachometer"
    target: "_self"
    is_shown: 1
  - code: "主页二"
    type: "menu"
    title: "主页二"
    href: "layuimini/page/welcome-2.html"
    icon: "fa fa-tachometer"
    target: "_self"
    is_shown: 1
  - code: "主页三"
    type: "menu"
    title: "主页三"
    href: "layuimini/page/welcome-3.html"
    icon: "fa fa-tachometer"
    target: "_self"
    is_shown: 1
  - code: "菜单管理"
    type: "menu"
    title: "菜单管理"
    icon: "fa fa-window-maximize"
    href: "layuimini/page/menu.html"
    target: "_self"
    is_shown: 1
  - code: "系统设置"
    type: "menu"
    title: "系统设置"
    icon: "fa fa-gears"
    href: "layuimini/page/setting.html"
    target: "_self"
    is_shown: 1
  - code: "表格示例"
    type: "menu"
    title: "表格示例"
    icon: "fa fa-file-text"
    href: "layuimini/page/table.html"
    target: "_self"
    is_shown: 1
  - code: "表单示例"
    type: "directory"
    title: "表单示例"
    icon: "fa fa-calendar"
    target: "_self"
    child: "普通表单|分步表单"
    is_shown: 1
  - code: "普通表单"
    type: "menu"
    title: "普通表单"
    href: "layuimini/page/form.html"
    icon: "fa fa-list-alt"
    target: "_self"
    is_shown: 1
  - code: "分步表单"
    type: "menu"
    title: "分步表单"
    href: "layuimini/page/form-step.html"
    icon: "fa fa-navicon"
    target: "_self"
    is_shown: 1
  - code: "登录模板"
    type: "directory"
    title: "登录模板"
    icon: "fa fa-flag-o"
    target: "_self"
    child: "登录-1|登录-2|登录-3"
    is_shown: 1
  - code: "登录-1"
    type: "menu"
    title: "登录-1"
    href: "layuimini/page/login-1.html"
    icon: "fa fa-stumbleupon-circle"
    target: "_self"
    is_shown: 1
  - code: "登录-2"
    type: "menu"
    title: "登录-2"
    href: "layuimini/page/login-2.html"
    icon: "fa fa-viacoin"
    target: "_self"
    is_shown: 1
  - code: "登录-3"
    type: "menu"
    title: "登录-3"
    href: "layuimini/page/login-3.html"
    icon: "fa fa-tags"
    target: "_self"
    is_shown: 1
  - code: "异常页面"
    type: "directory"
    title: "异常页面"
    icon: "fa fa-home"
    target: "_self"
    child: "404页面|失效菜单"
    is_shown: 1
  - code: "404页面"
    type: "menu"
    title: "404页面"
    href: "layuimini/page/404.html"
    icon: "fa fa-hourglass-end"
    target: "_self"
    is_shown: 1
  - code: "失效菜单"
    type: "menu"
    title: "失效菜单"
    href: "layuimini/page/error.html"
    icon: "fa fa-superpowers"
    target: "_self"
    is_shown: 1
  - code: "其它界面"
    type: "directory"
    title: "登录模板"
    icon: "fa fa-snowflake-o"
    target: ""
    child: "按钮示例|弹出层"
    is_shown: 1
  - code: "按钮示例"
    type: "menu"
    title: "按钮示例"
    href: "layuimini/page/button.html"
    icon: "fa fa-snowflake-o"
    target: "_self"
    is_shown: 1
  - code: "弹出层"
    type: "menu"
    title: "弹出层"
    href: "layuimini/page/layer.html"
    icon: "fa fa-shield"
    target: "_self"
    is_shown: 1
  - code: "组件管理"
    type: "head"
    title: "组件管理"
    icon: "fa fa-lemon-o"
    href: ""
    target: "_self"
    child: "图标列表|图标选择|颜色选择|下拉选择|文件上传|富文本编辑器|省市县区选择器"
    is_shown: 1
  - code: "图标列表"
    type: "menu"
    title: "图标列表"
    href: "layuimini/page/icon.html"
    icon: "fa fa-dot-circle-o"
    target: "_self"
    is_shown: 1
  - code: "图标选择"
    type: "menu"
    title: "图标选择"
    href: "layuimini/page/icon-picker.html"
    icon: "fa fa-adn"
    target: "_self"
    is_shown: 1
  - code: "颜色选择"
    type: "menu"
    title: "颜色选择"
    href: "layuimini/page/color-select.html"
    icon: "fa fa-dashboard"
    target: "_self"
    is_shown: 1
  - code: "下拉选择"
    type: "menu"
    title: "下拉选择"
    href: "layuimini/page/table-select.html"
    icon: "fa fa-angle-double-down"
    target: "_self"
    is_shown: 1
  - code: "文件上传"
    type: "menu"
    title: "文件上传"
    href: "layuimini/page/upload.html"
    icon: "fa fa-arrow-up"
    target: "_self"
    is_shown: 1
  - code: "富文本编辑器"
    type: "menu"
    title: "富文本编辑器"
    href: "layuimini/page/editor.html"
    icon: "fa fa-edit"
    target: "_self"
    is_shown: 1
  - code: "省市县区选择器"
    type: "menu"
    title: "省市县区选择器"
    href: "layuimini/page/area.html"
    icon: "fa fa-rocket"
    target: "_self"
    is_shown: 1